#
MODULE_NAME  FLASH_MACRONIX_NOR_OSPI
#
COMPILE_FILE ARM_GPP   MacronixParams
COMPILE_FILE ARM_GPP   MacronixInstruction
COMPILE_FILE ARM_GPP   MacronixInterface
COMPILE_FILE ARM_GPP   MacronixCommand
COMPILE_FILE ARM_GPP   MacronixActionWrite
COMPILE_FILE ARM_GPP   MacronixRegisters
COMPILE_FILE ARM_GPP   FlashManagerMacronix25LM
#
MODULE_PARAM MODULE_DEPEND OSPI
MODULE_PARAM MODULE_DEPEND FLASH_MANAGER

