#
MODULE_NAME  MAIN_USB_PRINTER
#
COMPILE_FILE ARM_GPP   MainUsbPrinter
#
MODULE_PARAM MODULE_DEPEND USB_MODULE
MODULE_PARAM MODULE_DEPEND LCD_MANAGER
MODULE_PARAM MODULE_DEPEND LED_MANAGER
MODULE_PARAM MODULE_DEPEND FLASH_MANAGER


