#ifndef _TYPE_OSPI_CONFIGURATION_PARAM_H_
#define _TYPE_OSPI_CONFIGURATION_PARAM_H_

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// @enum:     TypeOspiConfigurationParam
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
enum TypeOspiConfigurationParam
{
  OSPI_CONFIGURATION_PARAM_DEVICE_LOG_SIZE,
  OSPI_CONFIGURATION_PARAM_CLOCK_MAX_FREQUENCY,
  OSPI_CONFIGURATION_PARAM_CHIP_SELECT_HIGH_TIME,
  OSPI_CONFIGURATION_PARAM_CS_BOUNDARY_LOG_SIZE,
  OSPI_CONFIGURATION_PARAM_MAXIMUM_TRANSFER,
  OSPI_CONFIGURATION_PARAM_HYPERBUS_MEMORY_MAPPED,
  OSPI_CONFIGURATION_PARAM_HYPERBUS_READ_WRITE_RECOVERY_TIME,
  OSPI_CONFIGURATION_PARAM_HYPERBUS_ACCESS_TIME,
  OSPI_CONFIGURATION_PARAM_HYPERBUS_REFRESH_RATE,
  OSPI_CONFIGURATION_PARAM_HYPERBUS_FIXED_LATENCY,
  OSPI_CONFIGURATION_PARAM_HYPERBUS_WRITE_ZERO_LATENCY,
  OSPI_CONFIGURATION_PARAM_FIFO_THRESHOLD_LEVEL,
  OSPI_CONFIGURATION_PARAM_COUNT
};

#endif  // _TYPE_OSPI_CONFIGURATION_PARAM_H_
