#ifndef _TYPE_CLOCK_BUS_H_
#define _TYPE_CLOCK_BUS_H_

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// @enum:     TypeClockBus
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
enum TypeClockBus
{
  CLOCK_BUS_HSI_CK,
  CLOCK_BUS_CSI_CK,
  CLOCK_BUS_HSE_CK,
  CLOCK_BUS_SYS_CK,
  CLOCK_BUS_C_CK,
  CLOCK_BUS_FCLK_C,
  CLOCK_BUS_SYSTICK,
  CLOCK_BUS_ACLK,
  CLOCK_BUS_HCLK3,
  CLOCK_BUS_PCLK3,
  CLOCK_BUS_HCLK1,
  CLOCK_BUS_HCLK2,
  CLOCK_BUS_PCLK1,
  CLOCK_BUS_TIMX_KER_CK,
  CLOCK_BUS_RCC_PCLK2,
  CLOCK_BUS_TIMY_KEY_CK,
  CLOCK_BUS_HCLK4,
  CLOCK_BUS_FCLK_D3,
  CLOCK_BUS_RCC_PCLK4,
  CLOCK_BUS_GPIO_A,
  CLOCK_BUS_GPIO_B,
  CLOCK_BUS_GPIO_C,
  CLOCK_BUS_GPIO_D,
  CLOCK_BUS_GPIO_E,
  CLOCK_BUS_GPIO_F,
  CLOCK_BUS_GPIO_G,
  CLOCK_BUS_GPIO_H,
  CLOCK_BUS_GPIO_I,
  CLOCK_BUS_GPIO_J,
  CLOCK_BUS_GPIO_K,
  CLOCK_BUS_BACKUP_RAM,
  CLOCK_BUS_HSEM,
  CLOCK_BUS_ADC3,
  CLOCK_BUS_BDMA,
  CLOCK_BUS_CRC,
  CLOCK_BUS_PLL_SORUCE_CK,
  CLOCK_BUS_REF1_CK,
  CLOCK_BUS_VCO1_CK,
  CLOCK_BUS_PLL1_P,
  CLOCK_BUS_PLL1_Q,
  CLOCK_BUS_PLL1_R,
  CLOCK_BUS_REF2_CK,
  CLOCK_BUS_VCO2_CK,
  CLOCK_BUS_PLL2_P,
  CLOCK_BUS_PLL2_Q,
  CLOCK_BUS_PLL2_R,
  CLOCK_BUS_REF3_CK,
  CLOCK_BUS_VCO3_CK,
  CLOCK_BUS_PLL3_P,
  CLOCK_BUS_PLL3_Q,
  CLOCK_BUS_PLL3_R,
  CLOCK_BUS_OCTOSPI_KER_CK,

  CLOCK_BUS_COUNT
};

#endif  // _TYPE_CLOCK_BUS_H_

