#
LIBRARY_NAME APP_STM32H735
#
TARGET_NAME "basic_stm32h735"
#
TARGET_PARAM TARGET_EXE_NAME "basic_stm32h735_debug"
#
TARGET_PARAM ARM_TARGET_SCRIPT "PHYSICAL/STM32H735/system/stm32h735.ld"
#
#
TARGET_PARAM MODULE_DEPEND MAIN_BASIC
TARGET_PARAM MODULE_DEPEND LED_MANAGER
TARGET_PARAM MODULE_DEPEND FLASH_MANAGER
TARGET_PARAM MODULE_DEPEND LCD_MANAGER
